# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-deploy-fragments-376155441356-us-east-1"
    encrypt = true
    key     = "mb-dev-stratusgrid.tfstate"
    region  = "us-east-1"
  }
}
